### ISSUE TITLE
update annotation guidelines for new annotation scenario + tool

### ISSUE THREAD

**Issue by proycon** [knaw-huc/golden-agents-htr#10]

**Comment by proycon** [comment]
@HarmTseard  @brambg  Ik heb de annotatie guidelines geupdate, kunnen jullie hier al mee uit de voeten?

**Comment by brambg** [comment]
Ik wel, @HarmTseard , kijk je ook even of mijn [beknopte handleiding](https://ga-analiticcl-evaluate.tt.di.huc.knaw.nl/api/html/instructions.html) goed genoeg is voor [de tool](https://ga-analiticcl-evaluate.tt.di.huc.knaw.nl/) ?
