### ISSUE TITLE
Web Annotation output is partially undefined

### ISSUE THREAD

**Issue by proycon** [knaw-huc/golden-agents-htr#21]
We had a meeting a while back on the web annotation vocabulary and created a separate repository to gather examples: https://github.com/CLARIAH/webannotation-examples and initiated discussion in https://github.com/CLARIAH/webannotation-examples/issues/1 .

We didn't finish this yet however, and this is currently biting us as the JSON-LD output of the NER/analiticcl output does not have a full `@context` yet.  We need to make sure we add a `@context` (that is resolvable) so that all properties like `match_variant`, `match_phrase` have proper URIs.

The JSON-LD playground may help in testing to ensure our output is valid. This is a prerequisite for loading it into other tools.

After this is fixed, we should rerun the production experiment (takes a day or 3).

**Comment by brambg** [comment]
Ok, the  first step in making the annotations from the pipeline valid JSON-LD would be to add the proper @context for the custom fields.
If we take a current generated annotation as an example:
```
{
    "@context": [
      "http://www.w3.org/ns/anno.jsonld",
      "https://leonvanwissen.nl/vocab/roar/roar.json"
    ],
    "id": "3ca356e1-b8ff-489a-afa5-022a8462eb6c",
    "type": "Annotation",
    "motivation": "classifying",
    "generated": "2022-06-22T23:23:47.597149",
    "generator": {
      "id": "https://github.com/knaw-huc/golden-agents-htr",
      "type": "Software",
      "name": "GoldenAgentsNER"
    },
    "body": [
      {
        "type": "TextualBody",
        "value": "location",
        "modified": "2022-06-22T23:23:47.597073",
        "purpose": "tagging"
      },
      {
        "type": "TextualBody",
        "value": "West-Friesland",
        "modified": "2022-06-22T23:23:47.597090",
        "purpose": "commenting"
      },
      {
        "type": "Dataset",
        "value": {
          "match_phrase": "Westvrieslandt",
          "match_variant": "West-Friesland",
          "match_score": 0.8090909090909092,
          "match_source": [
            "locations_lexicon.freq.tsv",
            "int_historisch_lexicon_variants.freq.tsv"
          ],
          "category": "location",
          "seqnr": 1
        }
      }
    ],
    "target": {
      "source": "urn:golden-agents:2410_A27318:scan=A27318000439",
      "selector": [
        {
          "type": "TextPositionSelector",
          "start": 385,
          "end": 399
        },
        {
          "type": "TextQuoteSelector",
          "exact": "Westvrieslandt",
          "prefix": "Steden van ",
          "suffix": ", werdende"
        }
      ]
    }
  }

```
Then the `Dataset` `value` fields in the `body` don't have a `@context`
("https://leonvanwissen.nl/vocab/roar/roar.json" was an example custom context, but this url points to nowhere currently, and the ROAR ontology doesn't contain the fields we need anyway)

If we remove the roar link, and add a prefix for the Dataset values, we get this valid JSON-LD:
```
{
    "@context": [
      "http://www.w3.org/ns/anno.jsonld",
      {"ana": "http://purl.org/analiticcl/terms#"}
    ],
    "id": "3ca356e1-b8ff-489a-afa5-022a8462eb6c",
    "type": "Annotation",
    "motivation": "classifying",
    "generated": "2022-06-22T23:23:47.597149",
    "generator": {
      "id": "https://github.com/knaw-huc/golden-agents-htr",
      "type": "Software",
      "name": "GoldenAgentsNER"
    },
    "body": [
      {
        "type": "TextualBody",
        "value": "location",
        "modified": "2022-06-22T23:23:47.597073",
        "purpose": "tagging"
      },
      {
        "type": "TextualBody",
        "value": "West-Friesland",
        "modified": "2022-06-22T23:23:47.597090",
        "purpose": "commenting"
      },
      {
        "type": "ana:Match",
        "value": {
          "ana:match_phrase": "Westvrieslandt",
          "ana:match_variant": "West-Friesland",
          "ana:match_score": 0.8090909090909092,
          "ana:match_source": [
            "locations_lexicon.freq.tsv",
            "int_historisch_lexicon_variants.freq.tsv"
          ],
          "ana:category": "location",
          "ana:seqnr": 1
        }
      }
    ],
    "target": {
      "source": "urn:golden-agents:2410_A27318:scan=A27318000439",
      "selector": [
        {
          "type": "TextPositionSelector",
          "start": 385,
          "end": 399
        },
        {
          "type": "TextQuoteSelector",
          "exact": "Westvrieslandt",
          "prefix": "Steden van ",
          "suffix": ", werdende"
        }
      ]
    }
  }
```
In this JSON-LD, the roar link in `@context` is replaced by namespace definition
```
{"ana": "http://purl.org/analiticcl/terms#"}
```
where we would have to come up with a proper resolvable url instead of (or to link to from) http://purl.org/analiticcl/terms ,

and the `Dataset` `body` is replaced by a custom type `ana:Match`, where the `value` fields get the `ana` prefix:
```
      {
        "type": "ana:Match",
        "value": {
          "ana:match_phrase": "Westvrieslandt",
          "ana:match_variant": "West-Friesland",
          "ana:match_score": 0.8090909090909092,
          "ana:match_source": [
            "locations_lexicon.freq.tsv",
            "int_historisch_lexicon_variants.freq.tsv"
          ],
          "ana:category": "location",
          "ana:seqnr": 1
        }
      }
```
we'd have to discuss whether `Match` is the right name for this body type

Alternatively, we could define the custom fields in a custom `@context`:
```
"@context": [
      "http://www.w3.org/ns/anno.jsonld",
      {
		"Match": "http://purl.org/analiticcl/terms#Match",
		"match_phrase": "http://purl.org/analiticcl/terms#match_phrase",
		"match_variant": "http://purl.org/analiticcl/terms#match_variant",
		"match_score": "http://purl.org/analiticcl/terms#match_score",
		"match_source": "http://purl.org/analiticcl/terms#match_source",
		"category": "http://purl.org/analiticcl/terms#category",
		"seqnr": "http://purl.org/analiticcl/terms#seqnr",
	  }
]
```

or we can define and host our own custom context definition:
```
"@context": [
      "http://www.w3.org/ns/anno.jsonld",
      "http://humanities.knaw.nl/ns/analiticcl.jsonld",
]
```
But then we'd have to define this jsonld, and host it somewhere.

**Comment by brambg** [comment]
Also, https://github.com/CLARIAH/webannotation-examples/issues/1 raises some questions w.r.t the generated web annotations: ( paging @LvanWissen )

- For the text correction we're currently using `"purpose": "commenting"`, because this is what recogito-js needs. In the 2nd-to-last example on the issue  `"purpose": "correction"` is mentioned. Is this the preferred, final `purpose` for text correction bodies?
- Are the last 2 examples the templates for the final `correction` and `tagging` bodies? (with proper custom context, of course)
  - Is there a provenance server in production at this stage that we can use for the `provenance` fields, and if so, what data should be stored there?  
  - for the `SpecificResource` bodies, can all the categories used in the pipeline be mapped to a vocab.getty url?

**Comment by brambg** [comment]
I've added a branch to implement the SpecificResource body option.
In de config i add getty urls for the ner categories:
https://github.com/knaw-huc/golden-agents-htr/blob/extend-annotation/experiments/nerconfig.exp14l.json#L23-L38
Can somebody check if i've picked the correct getty resource ids?

**Comment by proycon** [comment]
> Then the Dataset value fields in the body don't have a @context
> ("https://leonvanwissen.nl/vocab/roar/roar.json" was an example custom context, but this url points to nowhere currently, and the >ROAR ontology doesn't contain the fields we need anyway)
If we remove the roar link, and add a prefix for the Dataset values, we get this valid JSON-LD:

Right, Leon indeed said we should simply remove roar and define something for the dataset values.
The JSON-LD looks good to me.

> where we would have to come up with a proper resolvable url instead of (or to link to from) http://purl.org/analiticcl/terms ,

Agreed

> or we can define and host our own custom context definition:
> 
> ```json
> "@context": [
>       "http://www.w3.org/ns/anno.jsonld",
>       "http://humanities.knaw.nl/ns/analiticcl.jsonld",
> ]
> ```
> 
> But then we'd have to define this jsonld, and host it somewhere.

I like that option yes. we can just use purl.org or w3id.org for a persistent URL to some jsonld file on github right?

> we'd have to discuss whether Match is the right name for this body type

Indeed, debatable but sounds okay. It's also debatable whether the whole namespace needs to be called 'analiticcl' as some things are a bit more generic and I believe we're reusing some terms that marijn already used in his tool for Republic, but I don't mind either way and this is probably a good/quick way to go for now.

> I've added a branch to implement the SpecificResource body option.
> In de config i add getty urls for the ner categories:
> https://github.com/knaw-huc/golden-agents-htr/blob/extend-annotation/experiments/nerconfig.exp14l.json#L23-L38
> Can somebody check if i've picked the correct getty resource ids?

I'm missing the 'person' category (results of the context rules). I don't know much about getty, @LvanWissen  can probably say more about it, I agree linking to existing ontologies is a good idea. One thing I don't really like though is that the URIs are not readily interpretable (they use some abstract numeric ID), if those are the only thing landing in the web annotation output we lose a level of interpretability. We could alternatively start our own little SKOS(?) vocabulary and define sameAs relations to getty or whatever?

**Comment by brambg** [comment]
> we can just use purl.org or w3id.org for a persistent URL to some jsonld file on github

That's a good option! If not analiticcl, what subdomain do we use? golden-agents? Something more generic?

**Comment by proycon** [comment]
Perhaps something as generic as 'variant-matching'?  Then we can envision different tools, not just analiticcl (via the NER wrapper), outputting the same kind of vocabulary.

**Comment by brambg** [comment]
I made an example custom context and hosted it at https://brambg.github.io/namespaces/variant-matching.jsonld.
Linking to this custom context (inside the `Match` body, so the `Match` `source` does not interfere with the `target` `source`  results in:

```
{
    "@context": "http://www.w3.org/ns/anno.jsonld",
    "id": "3ca356e1-b8ff-489a-afa5-022a8462eb6c",
    "type": "Annotation",
    "motivation": "classifying",
    "generated": "2022-06-22T23:23:47.597149",
    "generator": {
      "id": "https://github.com/knaw-huc/golden-agents-htr",
      "type": "Software",
      "name": "GoldenAgentsNER"
    },
    "body": [
      {
        "type": "TextualBody",
        "value": "location",
        "modified": "2022-06-22T23:23:47.597073",
        "purpose": "tagging"
      },
      {
        "type": "TextualBody",
        "value": "West-Friesland",
        "modified": "2022-06-22T23:23:47.597090",
        "purpose": "commenting"
      },
      {
        "@context": "https://brambg.github.io/namespaces/variant-matching.jsonld",
        "type": "Match",
        "value": {
          "phrase": "Westvrieslandt",
          "variant": "West-Friesland",
          "score": 0.8090909090909092,
          "source": [
            "locations_lexicon.freq.tsv",
            "int_historisch_lexicon_variants.freq.tsv"
          ],
          "category": "location",
          "seqnr": 1
        }
      }
    ],
    "target": {
      "source": "urn:golden-agents:2410_A27318:scan=A27318000439",
      "selector": [
        {
          "type": "TextPositionSelector",
          "start": 385,
          "end": 399
        },
        {
          "type": "TextQuoteSelector",
          "exact": "Westvrieslandt",
          "prefix": "Steden van ",
          "suffix": ", werdende"
        }
      ]
    }
  }
```

**Comment by menzowindhouwer** [comment]
Voor CLARIAH is ook een, nu nog ongebruikte, w3id server opgezet: https://perma-id.clariah.nl/ met als backing: https://github.com/knaw-huc/perma-id. Volgens mij was GA de grote aanjager ;-)

**Comment by brambg** [comment]
Wat is de status hiervan? Het lijkt me nog niet echt "af":
- https://perma-id.clariah.nl/ heeft een verlopen certificaat
- https://github.com/knaw-huc/perma-id heeft maar één commit, waarin dingen opgeruimt zijn, en zo te zien alleen een search/replace gedaan is in de readme

**Comment by proycon** [comment]
> I made an example custom context and hosted it at https://brambg.github.io/namespaces/variant-matching.jsonld.

Looks good!  The question now indeed remains where to perma-host it (@menzowindhouwer?). Once this is solved I'd like to rerun the experimental pipeline (takes about two days) so the output refers to the proper context.

**Comment by proycon** [comment]
Since you now use `http://purl.org/variant-matching/terms#` as URI I'd assume you registered `variant-matching` with purl.org and have http://purl.org/variant-matching/terms redirect to https://brambg.github.io/namespaces/variant-matching.jsonld (or whereever else we decide to host it)? It would be best if the URIs are resolvable and I'm guessing purl can do that?

**Comment by brambg** [comment]
I hadn't done that yet, since there was a preference for using perma-id.clariah.nl.
But, as the corresponding github repo doesn't look active right now, I've registered variant-matching with purl.org, and added the suggested redirect.

**Comment by menzowindhouwer** [comment]
I would like to go with http://humanities.knaw.nl/ns/... in the end. But that domain still has to become available AFAIK. 

The certificate of https://perma-id.clariah.nl/  can be easily fixed. It should be production, so this never should have happened, and you would be its first user!

Both don't really solve the problem where the static files should be hosted, i.e. they are mainly redirect services. But for humanities.knaw.nl there is an inherent need, so it will be arranged there ...

**Comment by menzowindhouwer** [comment]
So you can generate your data with http://humanities.knaw.nl/ns/... in place, just be aware they won't resolve at the moment, but that should be fixed after the summerbreak ...

**Comment by menzowindhouwer** [comment]
leaves the question of HTTP vs HTTPS. I think the latter should have the preference nowadays and most servers will redirect you by default ... so https://humanities.knaw.nl/ns/...

**Comment by LvanWissen** [comment]
HTTPS please!

**Comment by brambg** [comment]
De Web Annotations die uit de analiticcl pipeline komen moeten in timbuctoo komen. (via https://data.goldenagents.org/ ?)
Timbuctoo accepteert zo te zien geen jsonld:

> Supported formats: ttl, trig, nt, nq, n3, xml

, maar een web annotation is prima te converteren naar één van de rdf formaten:

https://github.com/knaw-huc/golden-agents-htr/blob/master/scripts/jsonld-to-graph.py

Hierboven staan voorbeelden van hoe we de annotaties eruit moeten laten zien.
Kunnen we daar naar kijken en komen tot een voorlopig definitieve vorm?

Daarbij moeten dan deze vragen nog beantwoord worden:

- Waar moet de _target_ van de annotatie naar verwijzen?
Idealiter een id waardoor deze dataset makkelijk te koppelen is met bestaande GA datasets (bijv. _Stadsarchief Amsterdam: Index op notarieel archief_ of _na_20220216_)?
De scan op de transkribus iiif server?
De pagexml?

- Moet de web annotation een uniek iri id krijgen? Zo ja, hoe moet dat eruitzien, en waar moet het naar resolven?

In [Entity Extraction en Named Entity Recognition on the City Archive HTR](https://confluence.socialhistoryservices.org/pages/viewpage.action?pageId=64326415#GoldenAgentsWP1&WP4tasks-EntityExtractionenNamedEntityRecognitionontheCityArchiveHTR) word genoemd:

> linken aan de authority lists (stcn, ecartico)

Is dit nog wenselijk/haalbaar? En zo ja, moet die link dan ook al in de web annotatie verwerkt zijn?

**Comment by brambg** [comment]
This web annotation:
```json
{
    "@context": "http://www.w3.org/ns/anno.jsonld",
    "id": "urn:golden-agents:annotation:2478f4e5-ad39-4468-a043-369547cd33f0",
    "type": "Annotation",
    "motivation": "classifying",
    "generated": "2022-07-07T09:03:36.466172",
    "generator": {
        "id": "https://github.com/knaw-huc/golden-agents-htr",
        "type": "Software",
        "name": "GoldenAgentsNER"
    },
    "body": [
        {
            "type": "SpecificResource",
            "purpose": "tagging",
            "modified": "2022-07-07T09:03:36.466118",
            "source": {
                "id": "http://vocab.getty.edu/aat/300435247",
                "label": "familyname"
            }
        },
        {
            "type": "TextualBody",
            "value": "Alleen",
            "modified": "2022-07-07T09:03:36.466129",
            "purpose": "commenting"
        },
        {
            "@context": "https://brambg.github.io/namespaces/variant-matching.jsonld",
            "type": "Match",
            "value": {
                "phrase": "alleen",
                "variant": "Alleen",
                "score": 0.875,
                "source": [
                    "family_names_lexicon.tsv"
                ],
                "category": [
                    "familyname"
                ]
            }
        }
    ],
    "target": {
        "source": "urn:golden-agents:2357_NOTD00236:scan=NOTD00236000222",
        "selector": [
            {
                "type": "TextPositionSelector",
                "start": 5,
                "end": 11
            },
            {
                "type": "TextQuoteSelector",
                "exact": "alleen",
                "prefix": "",
                "suffix": " als Voochden ende"
            }
        ]
    }
}
```

would look like this in ttl:

```
@prefix as: <http://www.w3.org/ns/activitystreams#> .
@prefix dcterms: <http://purl.org/dc/terms/> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix oa: <http://www.w3.org/ns/oa#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix vm: <https://humanities.knaw.nl/ns/variant-matching#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<urn:golden-agents:annotation:2478f4e5-ad39-4468-a043-369547cd33f0> a oa:Annotation ;
    dcterms:issued "2022-07-07T09:03:36.466172"^^xsd:dateTime ;
    as:generator <https://github.com/knaw-huc/golden-agents-htr> ;
    oa:hasBody [ a oa:TextualBody ;
            dcterms:modified "2022-07-07T09:03:36.466129"^^xsd:dateTime ;
            rdf:value "Alleen" ;
            oa:hasPurpose oa:commenting ],
        [ a vm:VariantMatch ;
            rdf:value [ vm:category "familyname"^^xsd:string ;
                    vm:phrase "alleen"^^xsd:string ;
                    vm:score "0.875"^^xsd:float ;
                    vm:source "family_names_lexicon.tsv"^^xsd:string ;
                    vm:variant "Alleen"^^xsd:string ] ],
        [ a oa:SpecificResource ;
            dcterms:modified "2022-07-07T09:03:36.466118"^^xsd:dateTime ;
            oa:hasPurpose oa:tagging ;
            oa:hasSource <http://vocab.getty.edu/aat/300435247> ] ;
    oa:hasTarget [ oa:hasSelector [ a oa:TextPositionSelector ;
                    oa:end "11"^^xsd:nonNegativeInteger ;
                    oa:start "5"^^xsd:nonNegativeInteger ],
                [ a oa:TextQuoteSelector ;
                    oa:exact "alleen" ;
                    oa:prefix "" ;
                    oa:suffix " als Voochden ende" ] ;
            oa:hasSource <urn:golden-agents:2357_NOTD00236:scan=NOTD00236000222> ] ;
    oa:motivatedBy oa:classifying .

<http://vocab.getty.edu/aat/300435247> rdfs:label "familyname" .

<https://github.com/knaw-huc/golden-agents-htr> a as:Application ;
    foaf:name "GoldenAgentsNER" .
```

**Comment by LvanWissen** [comment]
Om JSON-LD te converteren, is het van belang dat de context resolvable is. Daarin vindt immers de vertaling plaats tussen json-key en URI. Totdat die ns resolvet, kunnen we de hele context meegeven in de annotaties, maar dan worden ze misschien wel wat groot. Of jouw namespace gebruiken.

Tot nu toe zijn geen van de URIs van GA resolvable. Ik maak ze wel op https://data.goldenagents.org/etc. Scans hebben daarin ook een URI, bijvoorbeeld: `https://data.goldenagents.org/datasets/saa/ead/017d9ee6a1d9ff9e1cb3a9a64d15052c/scans/A20026000003` (ik heb daarin een combinatie gepakt van id van het inventarisnummer (=permalink) en de scannaam).

Maar, je annoteert de tekst van een scan, niet de scan zelf. Daar moet dan misschien een aparte resource van gemaakt worden. Tenzij je met coördinaten werkt, want dan annoteer je de afbeelding. Dus, ik zou zeggen:
* We maken een nieuwe URI voor de tekst als target voor de TextSelectors
* We gebruiken de GA-Scan URI voor annotaties met een coördinaat (xywh of svg-selector)

En ja, die annotaties moeten een URI krijgen. Misschien kunnen we de GA-Scan URI pakken en daar wat achter zetten. Zoiets als (met bovenstaand voorbeeld): `https://data.goldenagents.org/datasets/saa/ead/017d9ee6a1d9ff9e1cb3a9a64d15052c/scans/A20026000003/annotations/2478f4e5-ad39-4468-a043-369547cd33f0`. Of als dit te complex is, dan pakken we een generieke GA-namespace: `https://data.goldenagents.org/datasets/annotations/<uuid>`. Die moeten uiteraard ooit resolvable worden.

**Comment by brambg** [comment]
Hoe kom ik achter het scan uri? 
Moet ik uit https://data.goldenagents.org/details/u692bc364e9d7fa97b3510c6c0c8f2bb9a0e5123b__na_20220216
een lijst halen die van de 1667192 `roar_Scan` entries `rdfs:label` aan `uri` koppelt?
Is die lijst dan dekkend genoeg?

**Comment by LvanWissen** [comment]
In dit voorbeeld: `https://data.goldenagents.org/datasets/saa/ead/017d9ee6a1d9ff9e1cb3a9a64d15052c/scans/A20026000003`

* `https://data.goldenagents.org/datasets/saa/ead/` is een prefix die verwijst naar onze datasets in Timbuctoo, van `saa` (Stadsarchief) en uit de `ead` van deze data. 
* `017d9ee6a1d9ff9e1cb3a9a64d15052c` is de identifier van een inventarisnummer, zoals die ook gebruikt wordt in de permalinks op de website van het Stadsarchief: https://archief.amsterdam/inventarissen/file/017d9ee6a1d9ff9e1cb3a9a64d15052c
* `scans` is weer een vaste prefix
* `A20026000003` is de naam van de bestandsnaam van de scan (JPG). 

Ik gebruik hierin dus de identifier die ook in de permalink van het archief gebruikt wordt. Die zouden dus uit de EAD van het Archief geplukt moeten worden. Er staat ergens wel zo'n dataset in Timbuctoo en/of Virtuoso, maar ik heb ook ooit een mapping gemaakt voor https://gitlab.com/uvacreate/vondel/notarissennetwerk-rdf . 

Zo'n inventarisnummer is uniek binnen een collectie, vandaar mijn keuze voor de identifier uit de permalink. De mapping kun je hier downloaden, met daarin 31.854 resultaten. Dit zou het hele Notariële Archief moeten beslaan. Zie: [inventory2identifier.csv](https://github.com/knaw-huc/golden-agents-htr/files/9159610/inventory2identifier.csv)

Met query:
```sparql
PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT DISTINCT ?inventoryNumber ?identifier WHERE {
  ?inventory a schema:Book ;
    schema:author ?notary ;
    schema:name ?inventoryNumber .
  
  BIND(STRAFTER(STR(?inventory), 'file/') AS ?identifier)
    
  FILTER(CONTAINS(STR(?inventory), 'archief'))
}
```

Toevoeging:
Het lastige is dat die scannamen niet in de EAD meegegeven worden. Daarmee voldoet het niet aan de standaard, maar daarmee zou je ook een EAD krijgen van een paar gigabyte. We weten dus niet op voorhand welke scans er in een inventarisnummer hangen. Transkribus gebruikt de labels (zoals '1A'). Misschien kun je dus een koppeling op dat niveau maken? 

Of, we moeten gewoon dat 'leesbare' inventarisnummer in de URI opnemen. Maar dan wel met het collectienummer (5075 voor NA) er ook bij.

**Comment by brambg** [comment]
@LvanWissen, Ik heb je `inventory2identifier.csv` verwerkt:

This Web Annotation:
```json
{
    "@context": "http://www.w3.org/ns/anno.jsonld",
    "id": "https://data.goldenagents.org/datasets/annotations/b9e1aebb-c3b9-4ec6-8d4a-8bd0e523ac9b",
    "type": "Annotation",
    "motivation": [
        "classifying",
        "editing"
    ],
    "generated": "2022-07-29T09:15:20.343404",
    "generator": {
        "id": "https://github.com/knaw-huc/golden-agents-htr",
        "type": "Software",
        "name": "GoldenAgentsNER"
    },
    "body": [
        {
            "type": "SpecificResource",
            "purpose": "tagging",
            "modified": "2022-07-29T09:15:20.343365",
            "source": {
                "id": "http://vocab.getty.edu/aat/300404651",
                "label": "firstname"
            }
        },
        {
            "type": "TextualBody",
            "value": "Aen",
            "modified": "2022-07-29T09:15:20.343374",
            "purpose": "editing"
        },
        {
            "@context": "https://brambg.github.io/ns/variant-matching.jsonld",
            "type": "Match",
            "phrase": "aen",
            "variant": "Aen",
            "score": 0.8000034225282215,
            "source": [
                "first_names_lexicon.sanitized.tsv"
            ],
            "category": [
                "firstname"
            ]
        }
    ],
    "target": [
        {
            "source": "https://data.goldenagents.org/datasets/saa/ead/99e35cc52b73daa9123762e201def4e1/texts/VBPD00008000253",
            "type": "Text",
            "selector": [
                {
                    "type": "TextPositionSelector",
                    "start": 12,
                    "end": 15
                },
                {
                    "type": "TextQuoteSelector",
                    "exact": "aen",
                    "prefix": "overleringe ",
                    "suffix": ""
                }
            ]
        },
        {
            "source": "https://data.goldenagents.org/datasets/saa/ead/99e35cc52b73daa9123762e201def4e1/scans/VBPD00008000253",
            "type": "Image",
            "selector": {
                "type": "FragmentSelector",
                "conformsTo": "http://www.w3.org/TR/media-frags/",
                "value": "xywh=900,84,565,109"
            }
        }
    ]
}
```
would produce this ttl:
```
@prefix as: <http://www.w3.org/ns/activitystreams#> .
@prefix dcterms: <http://purl.org/dc/terms/> .
@prefix dctypes: <http://purl.org/dc/dcmitype/> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix gaa: <https://data.goldenagents.org/datasets/annotations/> .
@prefix oa: <http://www.w3.org/ns/oa#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix vm: <https://humanities.knaw.nl/ns/variant-matching#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

gaa:b9e1aebb-c3b9-4ec6-8d4a-8bd0e523ac9b a oa:Annotation ;
    dcterms:issued "2022-07-29T09:15:20.343404"^^xsd:dateTime ;
    as:generator <https://github.com/knaw-huc/golden-agents-htr> ;
    oa:hasBody [ a oa:TextualBody ;
            dcterms:modified "2022-07-29T09:15:20.343374"^^xsd:dateTime ;
            rdf:value "Aen" ;
            oa:hasPurpose oa:editing ],
        [ a vm:VariantMatch ;
            vm:category "firstname"^^xsd:string ;
            vm:phrase "aen"^^xsd:string ;
            vm:score "0.8000034225282215"^^xsd:float ;
            vm:source "first_names_lexicon.sanitized.tsv"^^xsd:string ;
            vm:variant "Aen"^^xsd:string ],
        [ a oa:SpecificResource ;
            dcterms:modified "2022-07-29T09:15:20.343365"^^xsd:dateTime ;
            oa:hasPurpose oa:tagging ;
            oa:hasSource <http://vocab.getty.edu/aat/300404651> ] ;
    oa:hasTarget [ a dctypes:Text ;
            oa:hasSelector [ a oa:TextPositionSelector ;
                    oa:end "15"^^xsd:nonNegativeInteger ;
                    oa:start "12"^^xsd:nonNegativeInteger ],
                [ a oa:TextQuoteSelector ;
                    oa:exact "aen" ;
                    oa:prefix "overleringe " ;
                    oa:suffix "" ] ;
            oa:hasSource <https://data.goldenagents.org/datasets/saa/ead/99e35cc52b73daa9123762e201def4e1/texts/VBPD00008000253> ],
        [ a dctypes:StillImage ;
            oa:hasSelector [ a oa:FragmentSelector ;
                    dcterms:conformsTo <http://www.w3.org/TR/media-frags/> ;
                    rdf:value "xywh=900,84,565,109" ] ;
            oa:hasSource <https://data.goldenagents.org/datasets/saa/ead/99e35cc52b73daa9123762e201def4e1/scans/VBPD00008000253> ] ;
    oa:motivatedBy oa:classifying,
        oa:editing .

<http://vocab.getty.edu/aat/300404651> rdfs:label "firstname" .

<https://github.com/knaw-huc/golden-agents-htr> a as:Application ;
    foaf:name "GoldenAgentsNER" .
```

Ik neem maar even aan dat nog niet alle scans via `https://data.goldenagents.org/datasets/saa/ead/{archiveIdentifier}/scans/{pageId}`
te bereiken zijn, want uit een kleine sample kon ik geen "werkende" scan urls halen.

Het is me uit je toevoeging niet duidelijk hoe de urls er dan zouden moeten uitzien, kun je voorbeelden geven?

**Comment by LvanWissen** [comment]
Die URIs zijn enkel in de data te vinden als ze voorkomen in de A2A (=indexen), want uit de EAD-data krijg ik geen scannamen. Er moet dus een indexrecord op deze scan gemaakt zijn om hem al beschreven te hebben in de data. Voor een deel van de HTR zal dat dus niet gelden, omdat de HTR-data niet synchroon loopt met de beschikbare geïndexeerde akten (uit Alle Amsterdamse Akten). In dat geval heb je dus wel een URI voor de scan, maar is hij nog niet geïndexeerd. 

Misschien moet ik dus nog een bestandje maken voor alle bestanden in de TranskribusAPI van het SAA om wel een type en inventarisnummer etc. toe te voegen?

**Comment by brambg** [comment]
> Misschien moet ik dus nog een bestandje maken voor alle bestanden in de TranskribusAPI van het SAA om wel een type en inventarisnummer etc. toe te voegen?

Kan ik dan daarmee de URIs uit je toevoeging maken? Hoe moeten die eruitzien?

**Comment by LvanWissen** [comment]
Als je URIs de vorm `https://data.goldenagents.org/datasets/saa/ead/{archiveIdentifier}/scans/{pageId}` hebben dan moet dit goedkomen!

**Comment by brambg** [comment]
Ok, dat hebben ze nu.
Dan sluit ik hierbij dit issue, en kan @proycon het experiment nog eens draaien.

**Comment by proycon** [comment]
Is goed! Ik zal 'm opnieuw draaien
