### ISSUE TITLE
WA purpose for annotations

### ISSUE THREAD

**Issue by LvanWissen** [knaw-huc/golden-agents-htr#26]
> Also, https://github.com/CLARIAH/webannotation-examples/issues/1 raises some questions w.r.t the generated web annotations: ( paging @LvanWissen )
> 
> - For the text correction we're currently using `"purpose": "commenting"`, because this is what recogito-js needs. In the 2nd-to-last example on the issue  `"purpose": "correction"` is mentioned. Is this the preferred, final `purpose` for text correction bodies?
> - Are the last 2 examples the templates for the final `correction` and `tagging` bodies? (with proper custom context, of course)
>   - Is there a provenance server in production at this stage that we can use for the `provenance` fields, and if so, what data should be stored there?  
>   - for the `SpecificResource` bodies, can all the categories used in the pipeline be mapped to a vocab.getty url?

_Originally posted by @brambg in https://github.com/knaw-huc/golden-agents-htr/issues/21#issuecomment-1170060302_

**Comment by LvanWissen** [comment]
A list of purposes is available under section '3.3.5 Motivation and Purpose' here: https://www.w3.org/TR/annotation-model/#motivation-and-purpose. 

I think the `commenting` does not fit what we do. It is allowed to add custom motivations/purposes (since the IIIF Presentation spec (https://iiif.io/api/presentation/3.0/) adds 'painting' and 'supplementing'), so I think using the `correction` is fine. Or, to keep the verb tense consistent: `correcting`. 

Maybe both `correcting` and `classifying` should be added in the `motivation` on the entire Annotation?

**Comment by brambg** [comment]
If we're going to use `correcting` as our custom `motivation`, then we'd need a context/namespace for it.
If I add it to my `variant-matching.jsonld`, then:

This Web Annotation:
```json
{
    "@context": [
        "https://brambg.github.io/namespaces/variant-matching.jsonld",
        "http://www.w3.org/ns/anno.jsonld"
    ],
    "id": "urn:golden-agents:annotation:2478f4e5-ad39-4468-a043-369547cd33f0",
    "type": "Annotation",
    "motivation": [
        "classifying",
        "correcting"
    ],
    "generated": "2022-07-07T09:03:36.466172",
    "generator": {
        "id": "https://github.com/knaw-huc/golden-agents-htr",
        "type": "Software",
        "name": "GoldenAgentsNER"
    },
    "body": [
        {
            "type": "SpecificResource",
            "purpose": "tagging",
            "modified": "2022-07-07T09:03:36.466118",
            "source": {
                "id": "http://vocab.getty.edu/aat/300435247",
                "label": "familyname"
            }
        },
        {
            "type": "TextualBody",
            "value": "Alleen",
            "modified": "2022-07-07T09:03:36.466129",
            "purpose": "correcting"
        },
        {
            "@context": "https://brambg.github.io/namespaces/variant-matching.jsonld",
            "type": "Match",
            "phrase": "alleen",
            "variant": "Alleen",
            "score": 0.875,
            "source": [
                "family_names_lexicon.tsv"
            ],
            "category": [
                "familyname"
            ]
        }
    ],
    "target": {
        "source": "urn:golden-agents:2357_NOTD00236:scan=NOTD00236000222",
        "selector": [
            {
                "type": "TextPositionSelector",
                "start": 5,
                "end": 11
            },
            {
                "type": "TextQuoteSelector",
                "exact": "alleen",
                "prefix": "",
                "suffix": " als Voochden ende"
            }
        ]
    }
}
```
would produce this ttl:
```
@prefix as: <http://www.w3.org/ns/activitystreams#> .
@prefix dcterms: <http://purl.org/dc/terms/> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix oa: <http://www.w3.org/ns/oa#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix vm: <https://humanities.knaw.nl/ns/variant-matching#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<urn:golden-agents:annotation:2478f4e5-ad39-4468-a043-369547cd33f0> a oa:Annotation ;
    dcterms:issued "2022-07-07T09:03:36.466172"^^xsd:dateTime ;
    as:generator <https://github.com/knaw-huc/golden-agents-htr> ;
    oa:hasBody [ a oa:TextualBody ;
            dcterms:modified "2022-07-07T09:03:36.466129"^^xsd:dateTime ;
            rdf:value "Alleen" ;
            oa:hasPurpose vm:correcting ],
        [ a oa:SpecificResource ;
            dcterms:modified "2022-07-07T09:03:36.466118"^^xsd:dateTime ;
            oa:hasPurpose oa:tagging ;
            oa:hasSource <http://vocab.getty.edu/aat/300435247> ],
        [ a vm:VariantMatch ;
            vm:category "familyname"^^xsd:string ;
            vm:phrase "alleen"^^xsd:string ;
            vm:score "0.875"^^xsd:float ;
            vm:source "family_names_lexicon.tsv"^^xsd:string ;
            vm:variant "Alleen"^^xsd:string ] ;
    oa:hasTarget [ oa:hasSelector [ a oa:TextQuoteSelector ;
                    oa:exact "alleen" ;
                    oa:prefix "" ;
                    oa:suffix " als Voochden ende" ],
                [ a oa:TextPositionSelector ;
                    oa:end "11"^^xsd:nonNegativeInteger ;
                    oa:start "5"^^xsd:nonNegativeInteger ] ;
            oa:hasSource <urn:golden-agents:2357_NOTD00236:scan=NOTD00236000222> ] ;
    oa:motivatedBy oa:classifying,
        vm:correcting .

<http://vocab.getty.edu/aat/300435247> rdfs:label "familyname" .

<https://github.com/knaw-huc/golden-agents-htr> a as:Application ;
    foaf:name "GoldenAgentsNER" .
```

Alternatively, the oa motivation `editing` might be similar enough to our intentions? 

> The motivation for when the user intends to request a change or edit to the Target resource. For example an Annotation that requests a typo to be corrected.

**Comment by LvanWissen** [comment]
Maybe that custom context only needs to be added once, for the entire object, and not in every subobject? 

Or, for the sake of not introducing a new motivation: let's go for `editing`!

**Comment by brambg** [comment]
I added the `variant-matching` context in the `Match` body because both the `variant-matching` and the `anno` contexts contain `source`.
Using the standard motivation `editing` will make the annotation simpler, so yeah, I'll use `editing`.
