### ISSUE TITLE
Add extra SpecificResource tying to specific object classes

### ISSUE THREAD

**Issue by proycon** [knaw-huc/golden-agents-htr#30]
We're adding URIs to the boedeltermen (#29), and want to tie the output of the NER pipeline to these specific URIs. You then get specific URIs for objects and our other categories (e.g. vase, knife). The NER pipeline needs to find these URIs based on the lexicon match and normalized output from analiticcl for a given word.

In the web annotation output this will amount to an extra body of `SpecificResource` with source pointing to the URI.

**Comment by brambg** [comment]
and a `label` with the lemma?

**Comment by proycon** [comment]
Right, a label with lemma makes sense.

**Comment by HarmTseard** [comment]
Working on it.

**Comment by proycon** [comment]
Implementation ready, waiting for @HarmTseard to deliver the data and will do some last fixes then and rerun the pipelines (#27 #28)
