### ISSUE TITLE
Missing archive identifiers

### ISSUE THREAD

**Issue by proycon** [knaw-huc/golden-agents-htr#31]
Whilst doing the final run, 547 files were skipped due to  missing archive identifiers! Something is clearly wrong, please see https://download.anaproy.nl/missing-archive-identifiers.log

**Comment by brambg** [comment]
If your folder with pagexml folders is similar to mine, then the files without archive identifiers are in an incorrectly named folder. The foldername should match with the title of the archive.

- `18892_KLAB05453/` - this should be `11892_KLAB05453/` ; in my pagexml folder I have both a `11892_KLAB05453` and a `18892_KLAB05453` folder, with identical pagexml files.
- `516NOTA00055/` - this folder should have been named `516_NOTA00055`; `archive_identifiers.csv` does have an entry for this latter name.
- `A16098/` - this folder should have been named `2408_A16098/`; in my pagexml folder I have both a `A16098` and a `2408_A16098` folder, but these are not identical.  `A16098` contains some lower-case named files, and from sampling some common files, it seems that for the files matching by name, `A16098` contains a more recent version, judging by the PcGts/Metadata/LastChanged elements.

So, if your pagexml folder is the same for the folders mentioned, you should:
- `rm -rf 18892_KLAB05453`
- `mv 516NOTA00055 516_NOTA00055`

and for the  `A16098` / `2408_A16098` situation, it might be better to delete both folders and re-download the pagexml?

and then re-run the pipeline for just the `516_NOTA00055` and `2408_A16098` folders, and merge the output of this run with the output of the previous final run.

**Comment by proycon** [comment]
Thanks for investigating!

* I did not have `11892_KLAB05453` yet so I renamed `18892_KLAB05453` to `11892_KLAB05453`
* `mv 516NOTA00055 516_NOTA00055`  - done

>  A16098 / 2408_A16098 situation, it might be better to delete both folders and re-download the pagexml?

Probably, though I'm first trying to see if we can get away with just copying from  `A16098/` to `2408_A16098/`, assuming the former are indeed more recent as you say. (mine are not lower-case named btw, the created date seems more recent indeed for most, lastupdated not always so)
